package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNationAllPropertiesEquals(Nation expected, Nation actual) {
        assertNationAutoGeneratedPropertiesEquals(expected, actual);
        assertNationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNationAllUpdatablePropertiesEquals(Nation expected, Nation actual) {
        assertNationUpdatableFieldsEquals(expected, actual);
        assertNationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNationAutoGeneratedPropertiesEquals(Nation expected, Nation actual) {
        assertThat(expected)
            .as("Verify Nation auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNationUpdatableFieldsEquals(Nation expected, Nation actual) {
        assertThat(expected)
            .as("Verify Nation relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNationUpdatableRelationshipsEquals(Nation expected, Nation actual) {
        // empty method
    }
}
