package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TopicAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicAllPropertiesEquals(Topic expected, Topic actual) {
        assertTopicAutoGeneratedPropertiesEquals(expected, actual);
        assertTopicAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicAllUpdatablePropertiesEquals(Topic expected, Topic actual) {
        assertTopicUpdatableFieldsEquals(expected, actual);
        assertTopicUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicAutoGeneratedPropertiesEquals(Topic expected, Topic actual) {
        assertThat(expected)
            .as("Verify Topic auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicUpdatableFieldsEquals(Topic expected, Topic actual) {
        assertThat(expected)
            .as("Verify Topic relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTopicUpdatableRelationshipsEquals(Topic expected, Topic actual) {
        assertThat(expected)
            .as("Verify Topic relationships")
            .satisfies(e -> assertThat(e.getMovies()).as("check movies").isEqualTo(actual.getMovies()));
    }
}
